#!/bin/bash

echo -e '\e[48;5;0m\e[38;5;214m'
echo -e '                                                          '
echo -e '  $$$$$$      $$$$$$    $$        $$  $$$$$$$   $$$$$$$   '
echo -e '$$      $$  $$      $$  $$$$      $$         $         $  '
echo -e '$$      $$  $$      $$  $$  $$    $$        $         $   '
echo -e '  $$$$$$      $$$$$$    $$    $$  $$       $         $    '
echo -e '$$      $$  $$      $$  $$      $$$$      $         $     '
echo -e '$$      $$  $$      $$  $$        $$     $         $      '
echo -e '  $$$$$$      $$$$$$    $$        $$    $         $       '
echo -e '                                                          '
echo -e '                                                          '
echo -e 'communication: https://t.me/n88n77crypt                   '
echo -e '                                                          '
echo -e '\e[0m'
